NUM_DOTS = 700
STEP_SIZE = 0.95
TOTAL_STEPS = 700
PLOT_LIMIT = 200

DEFAULT_FOOD_COUNT = 100
MIN_FOOD_COUNT = 5
MAX_FOOD_COUNT = 300

DEFAULT_FOOD_CLUSTER_SPREAD = 8.0
MIN_FOOD_CLUSTER_SPREAD = 2.0
FOOD_RADIUS = 1.0

AGENT_RADIUS = 0.55
FPS = 150
EAT_COOLDOWN_SECONDS = 1.0

BASE_DIRECTION_RESET_STEPS = 80
MIN_DIRECTION_CHANGE_DEGREES = 60
DIRECTION_NOISE_SCALE = 0.65
LEVY_FLIGHT_PROBABILITY = 0.07
LEVY_FLIGHT_MULTIPLIER_MIN = 2.0
LEVY_FLIGHT_MULTIPLIER_MAX = 4.5

MEMORY_SIZE = 3
MEMORY_SCORE_DECAY = 0.995
MEMORY_DISTANCE_MERGE = 10.0
MEMORY_REVISIT_STRENGTH = 0.32

INITIAL_PATCH_RADIUS = 12.0
MIN_PATCH_RADIUS = 4.0
MAX_PATCH_RADIUS = 18.0
PATCH_TIMEOUT_STEPS = 20
PATCH_TIMEOUT_GROWTH = 8
PATCH_RADIUS_SHRINK_FACTOR = 0.82
PATCH_RADIUS_GROWTH_FACTOR = 1.08
PATCH_CONFIDENCE_GAIN = 1.0
PATCH_CONFIDENCE_DECAY = 0.985

FORAGE_PULL_STRENGTH = 0.32
FORAGE_TANGENT_STRENGTH = 0.52
FORAGE_DIRECTION_BLEND = 0.16
LOCAL_WANDER_SCALE = 0.22
FORAGE_SPEED_REDUCTION = 0.72

SCENT_RADIUS = 1000.0
SCENT_STRENGTH = 0.4
INSPECTION_SPEED_REDUCTION = 0.86

SOCIAL_SIGNAL_RADIUS = .0
SOCIAL_SIGNAL_STRENGTH = 0.4
SOCIAL_SIGNAL_LIFETIME = 35

USE_BOUNDARY_REFLECTION = True